name: Deploy node application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create .env file
        run: echo "CONNECTION_URL=${{ secrets.CONNECTION_URL }}" > .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t bpraneeth/recyclotron-be .
      - name: Push docker image
        run: docker push bpraneeth/recyclotron-be:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image form dockerhub
        run: docker pull bpraneeth/recyclotron-be:latest
      - name: delete old container
        run: docker container rm -f nodejs-app-container
      - name: Run the container
        run: docker run -d -p 4000:3000 --name nodejs-app-container bpraneeth/recyclotron-be
      